# Generated by Django 3.2.7 on 2021-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDL_APP1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
